### ISSUE TITLE
fileRegex not applied to new files

### ISSUE THREAD

**Issue by paton** [nicjansma/node-handlebars-precompiler#11]
This is caused by a bug in the `watch` module. A fix has been merged (https://github.com/mikeal/watch/pull/62), but hasn't been published to NPM yet. 

Adding this issue as a reminder that `watch` should be upgraded once the new version is published.

**Comment by nicjansma** [comment]
Resolved with https://github.com/nicjansma/node-handlebars-precompiler/commit/a0fe3f6dfc685520afde31aca5d7eb89e8400b2d
