### ISSUE TITLE
Handlebars.templates is undefined for pre-compiled templates

### ISSUE THREAD

**Issue by skumar568** [nicjansma/node-handlebars-precompiler#18]
Hi,

I configured template pre-compilation as below:

```
const hbsPrecompiler = require('handlebars-precompiler');
const opts = {
  extensions : ['html'],	
};

hbsPrecompiler.watch(
  './templates',
  './templates/output.js',
  opts
);
```

When I am using the pre-compiled templates, I am getting 'undefined' error. Sample code is below:-

```
var Handlebars = require('handlebars/runtime');
console.log(Handlebars.templates['output']);
```

Could anyone please point if I missed anything here?

Thanks,
Sanjeev

**Comment by nicjansma** [comment]
@skumar568 Is `Handlebars` a real object?  Is `Handlebars.template` a function?

**Comment by skumar568** [comment]
I followed the link available for handlebar pre-compile module. Could you please provide any sample?

**Comment by nicjansma** [comment]
@skumar568 Can you share the results of my questions above?

Where are you loading `output.js`?

**Comment by nicjansma** [comment]
Please re-open if you have details
